biaci_go/urls.py
from django.contrib import admin
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf.urls import url
from django.urls import include, path

#from libro.views import views


urlpatterns = [
	path('', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')), 
    path('admin/', admin.site.urls),
    path('libro/', include('libro.urls'), name='ver_libro'),
    path('reserva/', include('reserva.urls'), name='reserva'),
    path('perfil/', include('prestamo.urls'), name='prestamo'),
    path('revista/', include('revista.urls'), name='ver_revista'),
    path('tesis/', include('tesis.urls'), name='ver_tesis'),
    path('', include('consulta.urls'), name='consulta'),
    path('reset/password_reset',password_reset,{
        'template_name':'PasswordReset/password_reset_form.html',
        'email_template_name':'PasswordReset/password_reset_email.html'},
        name="password_reset"), 
    path('password_reset_done',password_reset_done,{
        'template_name':'PasswordReset/password_reset_done.html'},
        name="password_reset_done"), 
    path('reset/(?P<uidb64>[0-94-Za-z_\-]+)/(?P<token>.+)/$',password_reset_confirm,{
        'template_name':'PasswordReset/password_reset_confirm.html'},
        name="password_reset_confirm"), 
    path('reset/done',password_reset_complete,{'template_name':'PasswordReset/password_reset_complete.html'},
        name="password_reset_complete")
]

libro/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.buscador, name='buscador_libro'),
    path('libros/', views.LibrosVista.as_view(), name='libros'),
    #path('libros/', views.LibrosVista, name='libro'),
    path('<pk>/libros/', views.EjemplaresVista.as_view(), name='ejemplar'),
    path('consulta/', views.ConsultaTodo.as_view(), name='consulta'),
    #path('autor/<pk>', views.EjemplaresVista.as_view(), name='detalle-autor'),
]

revista/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.buscador, name='buscador_revista'),
    path('revistas/', views.RevistaVista.as_view(), name='revistas'),
    path('<pk>/revistas/', views.EjemplaresVista.as_view(), name='ejemplar_revista'),
]

libro/models.py
from django.db import models

from django.urls import reverse  # Usado para generar URL

from django.core.validators import RegexValidator

ESTADO_EJEMPLAR = (
    ('P', 'Prestado'),
    ('D', 'Disponible'),
    ('B', 'Bloqueado'),  # ejemplares de consulta interna
    ('R', 'Reservado'),
)


class Biblioteca(models.Model):
    """
    Modelo que representa un biblioteca de la ULA

    :Example:
        Biaci, Trujillo, etc.
    """
    codigo = models.CharField(max_length=10, primary_key=True)
    nombre = models.CharField(max_length=100)
    estado = models.CharField(max_length=80)
    ciudad = models.CharField(max_length=80)
    avenida = models.CharField(max_length=80)
    calle = models.CharField(max_length=80)
    edificio = models.CharField(max_length=80)

    def __str__(self):
        """
        Cadena para representar el objeto en Admin
        """
        return self.nombre


class Materia(models.Model):
    """
    Modelo que representa una materia
    """
    nombre = models.CharField(max_length=20)

    def __str__(self):
        """
        Cadena para representar el objeto en Admin
        """
        return self.nombre


class Idioma(models.Model):
    """
    Modelo que representa un lenguaje

    :Example:
        ej. español, ingles, etc.
    """
    nombre = models.CharField(max_length=50)

    def __str__(self):
        """
        Cadena que representa el modelo objeto
        """
        return self.nombre


class Autor(models.Model):
    """
    Representacion del modelo Autor.
    """
    nombre = models.CharField(max_length=20)
    apellido = models.CharField(max_length=20)

    class Meta:
        """
        Clase para ordenar al momento de consultar
        """
        ordering = ["apellido", "nombre"]

    def get_absolute_url(self):
        """
        Retorna la url para ver detalles de autor.
        """
        return reverse('detalle-autor', args=[str(self.id)])

    def __str__(self):
        """
        Cadena para representar el objeto.
        :Example:
            Apellido, Nombre
        """
        return '{0}, {1}'.format(self.apellido, self.nombre)


class Libro(models.Model):
    """
    Modelo que representa un libro (pero no un ejemplar para prestar).
    """
    cota = models.CharField(max_length=20, primary_key=True)
    titulo = models.CharField(max_length=150)
    anio = models.PositiveSmallIntegerField()
    lugar_publicacion = models.TextField(max_length=50)
    editorial = models.CharField(max_length=50)
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    descripcion = models.TextField(max_length=1000)
    idioma = models.ForeignKey('Idioma', on_delete=models.SET_NULL, null=True)
    biblioteca = models.ForeignKey('Biblioteca', on_delete=models.SET_NULL, null=True)
    url = models.URLField()

    upload_path = 'images/portada'
    file_save_dir = '/images/portada/'

    # Campos para portada de libro
    imagen = models.ImageField(upload_to=upload_path, default='/images/portada/default.png')
    imagen_url = models.URLField()

    def save(self, *args, **kwargs):
        """
        Funcion que descargar la portada del libro pasada por el url y lo guarda localmente

        :param args: Parametro Vacio
        :param kwargs: Parametro Vacio
        :return: una funcion de guardar.
        """
        if self.imagen_url:
            import urllib, os, urllib.request
            from urllib.parse import urlparse
            filename = urlparse(self.imagen_url).path.split('/')[-1]
            # Guarda la imagen localmente despues de descargarla
            urllib.request.urlretrieve(self.imagen_url, os.path.join('static/images/portada/', filename))
            # Le guarda la ruta en el modelo donde esta la imagen local
            self.imagen = os.path.join(self.upload_path, os.path.join(self.file_save_dir, filename))
            super(Libro, self).save()

    autor = models.ManyToManyField(Autor)
    materia = models.ManyToManyField(Materia)

    def __str__(self):
        """
        Cadena para representar el objeto
        """
        return self.cota

    def get_absolute_url(self):
        """
        Devuelve la url para acceder a un registro de este libro
        """
        return reverse('ejemplar', args=[str(self.cota)])


class Ejemplar(models.Model):
    """
    Modelo que representa un ejemplar de un libro
    """
    ejemplar = models.CharField(
        max_length=4,
        validators=[RegexValidator(regex="^[e]{1}[0-9]{1,3}$", message="Formato de ejemplar incorrecto, ej: e1")],
    )
    libro = models.ForeignKey('Libro', on_delete=models.SET_NULL, null=True)
    estado = models.CharField(max_length=1, choices=ESTADO_EJEMPLAR, blank=True, default='D')

    def __str__(self):
        """
        Cadena para representar el objeto
        """
        return '{0} ({1})'.format(self.libro.cota, self.ejemplar)
        # return f'{self.id} ({self.book.title})'

    class Meta:
        """
        Simulacion de clave compuesta con campo unico tipo tupla
        """
        unique_together = (("ejemplar", "libro"),)

    def get_absolute_url(self):
        """
        Devuelve la url para acceder a un registro de este ejemplar
        """
        return reverse('detalle-ejemplar', args=[str(self.id)])

revista/models.py
from django.db import models

from libro.models import Idioma, Biblioteca, Materia

from django.urls import reverse  # Usado para generar URL

from django.core.validators import RegexValidator

ESTADO_EJEMPLAR = (
    ('B', 'Bloqueado'),  # ejemplares de consulta interna
)


class Revista(models.Model):
    """
    Modelo que representa una revista (pero no un ejemplar para prestar).
    """
    cota = models.CharField(max_length=20, primary_key=True)
    titulo = models.CharField(max_length=150)
    anio = models.PositiveSmallIntegerField()
    idioma = models.ForeignKey(Idioma, on_delete=models.SET_NULL, null=True)
    lugar_publicacion = models.TextField(max_length=50)
    descripcion = models.TextField(max_length=1000)
    numero = models.CharField(max_length=30)
    serie = models.CharField(max_length=30)
    biblioteca = models.ForeignKey(Biblioteca, on_delete=models.SET_NULL, null=True)
    area = models.CharField(max_length=30)
    url = models.URLField()

    upload_path = 'images/portada'
    file_save_dir = '/images/portada/'

    # Campos para portada de libro
    imagen = models.ImageField(upload_to=upload_path, default='/images/portada/default.png')
    imagen_url = models.URLField()

    def save(self, *args, **kwargs):
        """
        Funcion que descargar la portada del libro pasada por el url y lo guarda localmente

        :param args: Parametro Vacio
        :param kwargs: Parametro Vacio
        :return: una funcion de guardar.
        """
        if self.imagen_url:
            import urllib, os, urllib.request
            from urllib.parse import urlparse
            filename = urlparse(self.imagen_url).path.split('/')[-1]
            # Guarda la imagen localmente despues de descargarla
            urllib.request.urlretrieve(self.imagen_url, os.path.join('static/images/portada/', filename))
            # Le guarda la ruta en el modelo donde esta la imagen local
            self.imagen = os.path.join(self.upload_path, os.path.join(self.file_save_dir, filename))
            super(Revista, self).save()

    def __str__(self):
        """
        Cadena para representar el objeto
        """
        return self.cota

    def get_absolute_url(self):
        """
        Devuelve la url para acceder a un registro de esta revista
        """
        return reverse('ejemplar_revista', args=[str(self.cota)])
        #return "/revista/%i/" % self.cota


class EjemplarRevista(models.Model):
    """
        Modelo que representa un ejemplar de una revista
    """
    ejemplar = models.CharField(
        max_length=4,
        validators=[RegexValidator(regex="^[e]{1}[0-9]{1,3}$", message="Formato de ejemplar incorrecto, ej: e1")],
    )
    revista = models.ForeignKey('Revista', on_delete=models.SET_NULL, null=True)
    estado = models.CharField(max_length=1, choices=ESTADO_EJEMPLAR, blank=True, default='B')

    def __str__(self):
        """
        Cadena para representar el objeto
        """
        return '{0} ({1})'.format(self.revista.cota, self.ejemplar)
        # return f'{self.id} ({self.book.title})'

    class Meta:
        """
        Simulacion de clave compuesta con campo unico tipo tupla
        """
        unique_together = (("ejemplar", "revista"),)

    def get_absolute_url(self):
        """
        Devuelve la url para acceder a un registro de este ejemplar
        """
        return reverse('detalle-ejemplar-revista', args=[str(self.id)])

revista/forms.py
from django import forms

from .models import Revista

from libro.models import Biblioteca


Options = (
        ('0', 'Titulo'),
        ('1', 'Serie'),
        ('2', 'Cota'),
     )


class ConsultaRevistaForm(forms.ModelForm):

    buscar_por = forms.ChoiceField(label='Buscar por', widget=forms.Select, choices=Options)
    biblioteca = forms.ModelChoiceField(
        label='Biblioteca',
        queryset=Biblioteca.objects.all(),
        required=False
    )

    class Meta:
        model = Revista
        fields = (
            'titulo',
        )

    def limpiar_palabra(self):

        data = self.cleaned_data['limpiar_palabra']

        return data

revista/views.py
from django.template.response import TemplateResponse

from django.http import HttpResponseRedirect

from django.shortcuts import render, get_object_or_404


from django.views.generic import View


from revista.models import Revista

from reserva.models import Reserva

from consulta.models import Consulta


from .forms import ConsultaRevistaForm


def buscador(request):

    if request.method == 'POST':

        form = ConsultaRevistaForm(request.POST)
        if form.is_valid():
            return HttpResponseRedirect('/thanks/')
    else:
        form = ConsultaRevistaForm()

    return render(request, 'buscar_revista.html', {'form': form})


class RevistaVista(View):

    def post(self, request, *args, **kwargs):

        palabra = request.POST['titulo']

        biblioteca = request.POST['biblioteca']
        por = request.POST['buscar_por']

        if por == '0' and biblioteca == '':
            consulta = Revista.objects.filter(titulo__icontains=palabra)

        if por == '1' and biblioteca == '':
            consulta = Revista.objects.filter(serie__icontains=palabra)

        if por == '2' and biblioteca == '':
            consulta = Revista.objects.filter(cota__icontains=palabra)

        if por == '0' and biblioteca != '':
            consulta = Revista.objects.filter(titulo__icontains=palabra, biblioteca=biblioteca)

        if por == '1' and biblioteca != '':
            consulta = Revista.objects.filter(serie__icontains=palabra, biblioteca=biblioteca)

        if por == '3' and biblioteca != '':
            consulta = Revista.objects.filter(cota__icontains=palabra, biblioteca=biblioteca)

        return TemplateResponse(request, 'revista.html', {'consulta': consulta, 'palabra':palabra})


class EjemplaresVista(View):

    def get(self, request, pk, **kwargs):

        try:
            revista = Revista.objects.get(pk=pk)
        except Revista.DoesNotExist:
            raise Http404("La Revista no existe")

        # Verifico que no haya ningun ejemplar reservado y lo envio en la vista
        #reserva = Reserva.objects.filter(id_ejemplar__revista__cota=pk)
        #reservado = reserva.exists()
        print(revista.area)
        # Verifico si el titulo no esta en las consultas para agregarlo si no esta
        if Consulta.objects.filter(username=request.user, titulo=revista.titulo).exists() == False:
            busqueda = Consulta(username=request.user,cota=revista.cota,titulo=revista.titulo,autor_nombre=" ",autor_apellido=" ",tipo_material="Revista",tema=revista.area)
            busqueda.save()

        return render(request,'ejemplar_revista.html',context={'ejemplar': revista,})

revista/templates/buscar.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

    <section>
        <header class="main">
            <h1>{% block heading %}Buscador de Libros<br>{% endblock %}</h1>
        </header>

            <form method="post" action="{% url 'libros' %}">

                {% csrf_token %}
                {{ form.as_p }}
                <!--<div class="4u$ 12u$(xsmall)">
                    Buscar por:
                    <div class="select-wrapper">
                        <select name="por" id="por">
                            <option value="0">Titulo</option>
                            <option value="1">Autor</option>
                            <option value="2">ISBN</option>
                            <option value="3">Cota</option>
                        </select>
                    </div>
                    Biblioteca:
                    <div class="select-wrapper">
                        <select name="biblioteca" id="biblioteca">
                            <option value="0"> Biblioteca</option>
                            {% for bibliotecas in biblioteca %}
                            <option value="{{bibliotecas.codigo}}">{{bibliotecas.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>-->
                <br>
                <div class="12u$">
                    <ul class="actions">
                        <li><input type="submit" value="Buscar" class="special" /></li>
                        <li><input type="reset" value="Limpiar" /></li>
                    </ul>
                </div>
            </form>

    </section>
    <!--Siempre van dos div que cierran-->
    </div>
</div>
{% endblock %}

revista/templates/buscar_revista.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

    <section>
        <header class="main">
            <h1>{% block heading %}Buscador de Libros<br>{% endblock %}</h1>
        </header>

            <form method="post" action="{% url 'revistas' %}">

                {% csrf_token %}
                {{ form.as_p }}
                <!--<div class="4u$ 12u$(xsmall)">
                    Buscar por:
                    <div class="select-wrapper">
                        <select name="por" id="por">
                            <option value="0">Titulo</option>
                            <option value="1">Autor</option>
                            <option value="2">ISBN</option>
                            <option value="3">Cota</option>
                        </select>
                    </div>
                    Biblioteca:
                    <div class="select-wrapper">
                        <select name="biblioteca" id="biblioteca">
                            <option value="0"> Biblioteca</option>
                            {% for bibliotecas in biblioteca %}
                            <option value="{{bibliotecas.codigo}}">{{bibliotecas.nombre}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>-->
                <br>
                <div class="12u$">
                    <ul class="actions">
                        <li><input type="submit" value="Buscar" class="special" /></li>
                        <li><input type="reset" value="Limpiar" /></li>
                    </ul>
                </div>
            </form>

    </section>
    <!--Siempre van dos div que cierran-->
    </div>
</div>
{% endblock %}

revista/templates/ejemplar.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

   <h1>Titulo: {{ ejemplar.titulo }}</h1>

  <p><strong>Autor:</strong> {% for autor in ejemplar.autor.all %} {{ autor }}{% if not forloop.last %}, {% endif %}{% endfor %}</p> <!-- author detail link not yet defined -->
  <p><strong>Descripci&oacute;n:</strong> {{ ejemplar.descripcion }}</p>
  <p><strong>ISBN:</strong> {{ ejemplar.isbn }}</p>
  <p><strong>Idioma:</strong> {{ ejemplar.idioma }}</p>
  <p><strong>Idioma:</strong> {{ ejemplar.biblioteca }}</p>
  <p><strong>Materias:</strong> {% for materia in ejemplar.materia.all %} {{ materia }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Ejemplares</h4>
    <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Cota</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for copy in ejemplar.ejemplar_set.all %}
                    <tr>
                        <td>{{copy.cota}} {{copy.ejemplar}}</td>
                        <td>
                            {% if copy.estado == 'P' %} Prestado {% endif %}
                            {% if copy.estado == 'D' %} Disponible {% endif %}
                            {% if copy.estado == 'B' %} Bloqueado {% endif %}
                        </td>
                        <td>
                            <a href="{{ libros.get_absolute_url }}" class="icon fa-search"></a>
                            {% if copy.estado == 'D' %}
                                <a href="{% url 'reservar' copy.id %}" class="icon fa-clock-o"></a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
  </div>
    <!--Siempre van dos div que cierran-->
    </div>
</div>
{% endblock %}

revista/templates/ejemplar_revista.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

   <h1>Titulo: {{ ejemplar.titulo }}</h1>

  <p><strong>Descripci&oacute;n:</strong> {{ ejemplar.descripcion }}</p>
  <p><strong>Numero:</strong> {{ ejemplar.numero }}</p>
  <p><strong>Serie:</strong> {{ ejemplar.serie }}</p>
  <p><strong>Año:</strong> {{ ejemplar.anio }}</p>
  <p><strong>Biblioteca:</strong> {{ ejemplar.biblioteca }}</p>
  <p><strong>Area:</strong> {{ ejemplar.area }}</p>
<div class="4u"><span class="image fit"><a href="{{ejemplar.url }}" class="image"><img src="{% static ejemplar.imagen.url  %}" alt="" /></a></span></div>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Ejemplares</h4>
    <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Cota</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for copy in ejemplar.ejemplarrevista_set.all %}
                    <tr>
                        <td>{{copy.cota}} {{copy.ejemplar}}</td>
                        <td>
                            {% if copy.estado == 'P' %} Prestado {% endif %}
                            {% if copy.estado == 'D' %} Disponible {% endif %}
                            {% if copy.estado == 'B' %} Bloqueado {% endif %}
                            {% if copy.estado == 'R' %} Reservado {% endif %}
                        </td>
                        <td>
                            <a href="{{ revistas.get_absolute_url }}" class="icon fa-search"></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
  </div>
    <!--Siempre van dos div que cierran-->
    </div>
</div>
{% endblock %}

revista/templates/revista.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}

    <section>
        <header class="main">
            <h1>{% block heading %}Catalogos de Revista <br>{% endblock %}</h1>
        </header>
        <h3>B&uacute;squeda por: {{palabra}}</h3>
        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Cota</th>
                        <th>T&iacute;tulo</th>
                        <th>Numero</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for revistas in consulta %}
                    <tr>
                        <td>{{revistas.cota}}</td>
                        <td>{{revistas.titulo}}</td>
                        <td>{{revistas.numero}}</td>
                        <td><a href="{{ revistas.get_absolute_url }}" class="icon fa-search"></a></td>
                    </tr>
                    {%empty%}
                     <tr>
                        <td colspan="4" class="align-center">No hay resultados que coincidan con la b&uacute;squeda</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
    <!--Siempre van dos div que cierran-->
    </div>
</div>
{% endblock %}